In [17]:
import numpy as np
import numpy.linalg as la

a = np.array([[1],[3],[7],[2]])


A = np.array([[1, 3, 7, 2], [5, 8, 9, 0], [6, 7, 11, 12]])

print("A =", A)
print("a =", a)


A = [[ 1  3  7  2]
 [ 5  8  9  0]
 [ 6  7 11 12]]
a = [[1]
 [3]
 [7]
 [2]]


In [18]:
A= np.array([[0, 1],[-2, -3]])

B =np.array([[1, 0],[3, -2]])

C = A + B 
print("A+B =", C)

C = A - B 
print ("A-B =", C)

C =A * B
print("A+B")

A+B = [[ 1  1]
 [ 1 -5]]
A-B = [[-1  1]
 [-5 -1]]
A+B


In [19]:
import numpy as np

# Define matrices using NumPy
matrix_a = np.array([[2, 3],
                      [4, 5]])
matrix_b = np.array([[1, 0],
                      [2, 1]])

# Matrix multiplication using NumPy
numpy_result = np.dot(matrix_a, matrix_b)
print("Matrix multiplication using NumPy:")
print(numpy_result)

# Element-wise multiplication using NumPy
element_wise_result = np.multiply(matrix_a, matrix_b)
print("\nElement-wise multiplication using NumPy:")
print(element_wise_result)

# Matrix addition using NumPy
numpy_addition = np.add(matrix_a, matrix_b)
print("\nMatrix addition using NumPy:")
print(numpy_addition)

# Matrix subtraction using NumPy
numpy_subtraction = np.subtract(matrix_a, matrix_b)
print("\nMatrix subtraction using NumPy:")
print(numpy_subtraction)

# Determinant using NumPy
numpy_determinant_a = np.linalg.det(matrix_a)
print("\nDeterminant of matrix A using NumPy:")
print(numpy_determinant_a)

# Inverse using NumPy
numpy_inverse_a = np.linalg.inv(matrix_a)
print("\nInverse of matrix A using NumPy:")
print(numpy_inverse_a)


Matrix multiplication using NumPy:
[[ 8  3]
 [14  5]]

Element-wise multiplication using NumPy:
[[2 0]
 [8 5]]

Matrix addition using NumPy:
[[3 3]
 [6 6]]

Matrix subtraction using NumPy:
[[1 3]
 [2 4]]

Determinant of matrix A using NumPy:
-2.0

Inverse of matrix A using NumPy:
[[-2.5  1.5]
 [ 2.  -1. ]]
